<?php

/*
 * Created by Listratsenka Stas
 * Version 1.0
 */

declare(strict_types=1);

class InvalidPackagesException extends Exception
{
    public function __construct(string $message, int $code = 0, Exception $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }

    public function __toString()
    {
        return __CLASS__ . ": [{$this->code}]: {$this->message}\n"; // TODO: Change the autogenerated stub
    }
}